# Site settings
name: Welcome To Liujw's Blog
email: 708912805@qq.com
author: LiuJingwen
url: https://ljw718.github.io/

resume_site: https://github.com/LJW718
github: https://github.com/LJW718/
baseurl: ''
description: 自己动手,丰衣足食!
meta_description: 自己动手,丰衣足食
motto: 自己动手,丰衣足食
banner: 不积跬步,无以至千里 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LJW718

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

# Gems
plugins: [jekyll-paginate]

