# Site settings
name: Welcome To My Blog
email: 708912805@qq.com
author: Liu JingWen
#url: http://www.hifreud.com
resume_site: https://github.com/LJW718
github: https://github.com/LJW718/
baseurl: ''
description: 拒绝做一个空想主义者!
meta_description: 活到老;学到老
motto: 活到老,学到老
banner: 不积跬步,无以至千里 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LJW718

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

